### ISSUE TITLE
Video setting cannot save data

### ISSUE THREAD

**Issue by diotsani** [Peek-Mee/comma-dev#15] opened 2022-12-20 13:52 UTC
maybe in class VideoSaveData

**Comment by msyariefh** [comment] 2022-12-21 00:54
in development mode, it's hard to reproduce this bug. I've checked in the VideoSaveData file, and no anomaly, everything is worked as intended.

Maybe we need to investigate this a bit further.

**Closed as completed** 2022-12-21 16:35 UTC
Labels: bug
